retail_electricity:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../data/retail_electricity.duckdb
      schema: dbt_models
    prod:
      type: duckdb
      path: ../data/retail_electricity.duckdb
      schema: dbt_models