version: 2

sources:
  - name: retail_electricity
    database: retail_electricity
    schema: retail_electricity_dlt
    tables:
      - name: standard_offer_df
      - name: customers_df
      - name: eia_df
      - name: load_df