name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ "main" ]  # Change to "master" if that's your default branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Optional: Add a schedule to rebuild periodically (useful for data that changes)
  # This example runs daily at midnight UTC
  # schedule:
  #   - cron: '0 0 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'  # Change to 'npm' if using npm

      - name: Install dependencies
        run: yarn install  # Change to 'npm ci' if using npm

      # Optional: Add a step to create a .nojekyll file to bypass Jekyll processing
      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Build project
        run: yarn build  # Change to 'npm run build' if using npm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # The folder containing the built site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4